# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: "3.10"
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: poetry
      - name: Install Poetry and dependencies
        run: |
          pipx install poetry==1.2.0
          poetry install
      - name: Run flake8 with reviewdog
        uses: reviewdog/action-flake8@v3.6.0
        with:
          workdir: .
          reporter: github-pr-check
          # Filtering mode for the reviewdog command [added, diff_context, file, nofilter].
          filter_mode: diff_context
